name: Go Code and Docker Image Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v7

      # 2. Setup Go
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'

      # 3. Install Trivy
      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3

      # 4. Check Trivy version
      - name: Check Trivy version
        run: trivy --version

      # 5. Scan Go project / source code
      - name: Trivy Code Scan
        run: |
          trivy fs \
            --scanners vuln,secret,misconfig \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            .

      # 6. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t YOUR_DOCKER_IMAGE:TAG .

      # 7. Scan Docker image
      - name: Trivy Docker Image Scan
        run: |
          trivy image \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            YOUR_DOCKER_IMAGE:TAG
